// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFYsZdlrJq20Jgjvn6ojc2RWsK6qmu2qU',
    appId: '1:37031961174:web:33fdefa035e20ca9ab51f7',
    messagingSenderId: '37031961174',
    projectId: 'go-egypt-9e91b',
    authDomain: 'go-egypt-9e91b.firebaseapp.com',
    storageBucket: 'go-egypt-9e91b.firebasestorage.app',
    measurementId: 'G-QT6E1CSM4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZagDjK7DWqKU-eAbQBVN73CemGRv_7sE',
    appId: '1:37031961174:android:5139b3701bd1f895ab51f7',
    messagingSenderId: '37031961174',
    projectId: 'go-egypt-9e91b',
    storageBucket: 'go-egypt-9e91b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTY4Ewdz1Gb73jg-aw3_tajlgsXDEqKdo',
    appId: '1:37031961174:ios:a2edd68c530ea74bab51f7',
    messagingSenderId: '37031961174',
    projectId: 'go-egypt-9e91b',
    storageBucket: 'go-egypt-9e91b.firebasestorage.app',
    iosBundleId: 'com.example.sprintsShoppingAppWithLocalization',
  );
}
